services:
  - type: web
    name: kravan-api
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: YOUR_APP_KEY_HERE
      - key: FILESYSTEM_DISK
        value: public
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: array